%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 899.8993371882239 #4.250258563372763e+02
Camera1.fy: 891.2688298342263 #4.267976260903337e+02
Camera1.cx: 481.7242199450654 #3.860151866550880e+02
Camera1.cy: 396.1787262902864 #2.419130336743440e+02

Camera1.k1: -0.28340811 #-0.288105327549552
Camera1.k2: 0.07395907 #0.074578284234601
Camera1.p1: 0.00019359 #7.784489598138802e-04
Camera1.p2: 1.76187114e-05 #-2.277853975035461e-04

# Camera resolution
Camera.width: 1280
Camera.height: 720

#Camera.newWidth: 640
#Camera.newHeight: 360

# Camera frames per second 
Camera.fps: 30

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# # # Transformation from camera to body-frame (imu)
# IMU.T_b_c1: !!opencv-matrix
#      rows: 4
#      cols: 4
#      dt: f
#      data: [0.0148655429818, -0.999880929698, 0.00414029679422, -0.0216401454975,
#            0.999557249008, 0.0149672133247, 0.025715529948, -0.064676986768,
#           -0.0257744366974, 0.00375618835797, 0.999660727178, 0.00981073058949,
#            0.0, 0.0, 0.0, 1.0]

#  # IMU noise
# IMU.NoiseGyro: 1.7e-4 #1.6968e-04
# IMU.NoiseAcc: 2.0000e-3 #2.0e-3
# IMU.GyroWalk: 1.9393e-05 
# IMU.AccWalk: 3.0000e-03 # 3e-03
# IMU.Frequency: 100.0

# RPY angles (in rad) the world frame will be rotated by
WorldRPY.roll: 1.57079632679 #1.91986 #1.74533 
WorldRPY.pitch: 0.0
WorldRPY.yaw: 1.57079632679

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1200 #5000 # 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -1.7
Viewer.ViewpointZ: 0.8
Viewer.ViewpointF: -500.0
Viewer.imageViewScale: 1.0

#--------------------------------------------------------------------------------------------
# Save and Load Atlas
#--------------------------------------------------------------------------------------------

# System.LoadAtlasFromFile: "./yourdirectory/atlas"
# System.SaveAtlasToFile: "./yourdirectory/atlas"

